BoardGame/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("world.urls")),
    path("user/", include("user.urls")),
    path("admin/", admin.site.urls),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("join/", views.join_page, name="join"),
    path("logout/", views.logout_page, name="logout"),
]

world/urls.py
from django.urls import path
from . import views


app_name = "world"

urlpatterns = [
    path("", views.index, name="index"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

user/forms.py
from django import forms
from django.db import models
from django.forms import fields
from .models import User


class SignupForm(forms.Form):
    ID = forms.CharField(label="ID", max_length=15)
    PW = forms.CharField(label="PW", widget=forms.PasswordInput)
    PW_C = forms.CharField(label="PW 확인", widget=forms.PasswordInput)
    first_name = forms.CharField(label="닉네임", max_length=10)


class LoginForm(forms.Form):
    ID = forms.CharField(label="ID", max_length=15)
    PW = forms.CharField(label="PW", widget=forms.PasswordInput)

user/views.py
from .models import User
from user.forms import SignupForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render


def login_page(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data["ID"]
            user_pw = form.cleaned_data["PW"]
            user = authenticate(request, username=user_id, password=user_pw)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("world:index"))
            else:
                messages.info(request, "아이디가 없거나 비밀번호가 잘못되었습니다.")
                return HttpResponseRedirect(reverse("user:login"))

    form = LoginForm()
    return render(request, "user/login.html", {"form": form})


def join_page(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data["ID"]
            if User.objects.filter(username=user_id).exists():
                messages.info(request, "이미 존재하는 유저이름입니다.")
            elif form.cleaned_data["PW"] != form.cleaned_data["PW_C"]:
                messages.info(request, "비밀번호가 서로 일치하지 않습니다.")
            else:
                user_pw = form.cleaned_data["PW"]
                first_name = form.cleaned_data["first_name"]
                add_list = User(username=user_id, first_name=first_name)
                add_list.set_password(user_pw)
                add_list.save()
                messages.info(request, "회원가입이 정상적으로 완료되었습니다.")
                return HttpResponseRedirect(reverse("world:index"))

    form = SignupForm()
    return render(request, "user/join.html", {"form": form})


def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse("world:index"))

world/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, "world/world.html")

user/templates/user/join.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>Board Game</title>
    {% load static %}
</head>

<body>
    <div>
        <p><회원 가입></p>
        <form action="{% url 'user:join' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" name="" value="추가하기">
        </form>
    </div>
        {% if messages %}
        {% for message in messages %}
        <script>alert("{{ message }}")</script>
        {% endfor %}
        {% endif %}
</body>

<footer>
    <section>
        <a href="https://github.com/Dezeli/BoardGame" target='_blank'></a>
        <p><small>&copy; 2024 Dezeli</small></p>
        <p><small>haterecursive@gmail.com</small></p>
    </section>
</footer>

</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>Board Game</title>
    {% load static %}
</head>

<body>
    <main>
        <div>
            <p><로그인></p>
            <form action="{% url 'user:login' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" name="" value="로그인">
            </form>
            {% if messages %}
            {% for message in messages %}
            <script>alert("{{ message }}")</script>
            {% endfor %}
            {% endif %}
        </div>
    </main>
</body>

<footer>
    <section>
        <a href="https://github.com/Dezeli/BoardGame" target='_blank'></a>
        <p><small>&copy; 2024 Dezeli</small></p>
        <p><small>haterecursive@gmail.com</small></p>
    </section>
</footer>

</html>

world/templates/world/world.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>Board Game</title>
    {% load static %}
</head>

<body>
    <nav>
        {% if not user.is_authenticated %}
        <aside>
            <a class="log" href="{% url 'user:login' %}">로그인</a>
            <a class="log" href="{% url 'user:join' %}">회원가입</a>
        </aside>
        {% else %}
        <aside>
            <a>환영합니다. {{ user.first_name }}님</a>
            <a class="log" href="{% url 'user:logout' %}">로그아웃</a>
        </aside>
        {% endif %}
    </nav>

    
</body>

<footer>
    <section>
        <a href="https://github.com/Dezeli/BoardGame" target='_blank'></a>
        <p><small>&copy; 2024 Dezeli</small></p>
        <p><small>haterecursive@gmail.com</small></p>
    </section>
</footer>

</html>